---
- hosts: nodes
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
    temp_folder: /tmp
  tasks:
    - include: tasks/prerequisites.yml
    - include: tasks/mongodb.yml
    - include: tasks/nodejs.yml